name: "Publish to Distributed Press"
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Distributed Press
      uses: hyphacoop/actions-distributed-press@v1.1.0
      with:
        publish_dir: "."
        dp_url: https://api.distributed.press
        refresh_token: ${{ secrets.DISTPRESS_TOKEN }}
        site_url: distpress.ffdweb.org
        deploy_http: true
        deploy_hyper: true
        deploy_ipfs: true
